"""Add columns for Kommunen

Revision ID: e92d725697d4
Revises: 5c1cab8be91c
Create Date: 2020-10-07 19:54:56.832795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92d725697d4'
down_revision = '5c1cab8be91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases_ac', sa.Column('alsdorf', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('baesweiler', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('eschweiler', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('herzogenrath', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('monschau', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('roetgen', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('simmerath', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('stolberg', sa.Integer(), nullable=True))
    op.add_column('cases_ac', sa.Column('wuerselen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases_ac', 'wuerselen')
    op.drop_column('cases_ac', 'stolberg')
    op.drop_column('cases_ac', 'simmerath')
    op.drop_column('cases_ac', 'roetgen')
    op.drop_column('cases_ac', 'monschau')
    op.drop_column('cases_ac', 'herzogenrath')
    op.drop_column('cases_ac', 'eschweiler')
    op.drop_column('cases_ac', 'baesweiler')
    op.drop_column('cases_ac', 'alsdorf')
    # ### end Alembic commands ###
