"""Save not located cases

Revision ID: de70e2ebea28
Revises: e92d725697d4
Create Date: 2020-11-07 14:19:24.200371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de70e2ebea28'
down_revision = 'e92d725697d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases_ac', sa.Column('not_associated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases_ac', 'not_associated')
    # ### end Alembic commands ###
