"""Initial Database

Revision ID: 5c1cab8be91c
Revises: 
Create Date: 2020-10-07 19:27:23.475513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1cab8be91c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases_ac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cases_region', sa.Integer(), nullable=True),
    sa.Column('cases_city', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases_ac')
    # ### end Alembic commands ###
